repos:
- repo: local
  hooks:
    - id: fix
      name: fix
      entry: bash -c 'pipenv run pre-commit-fix'
      language: system
    - id: format
      name: format
      entry: bash -c 'pipenv run pre-commit-format'
      language: system
    - id: test
      name: test
      entry: bash -c 'pipenv run test'
      language: system